# Generated by Django 4.2.16 on 2024-11-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='goal_weight_date',
            new_name='goal_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='current_weight',
        ),
        migrations.RemoveField(
            model_name='member',
            name='goal_weight',
        ),
        migrations.AddField(
            model_name='member',
            name='goal_description',
            field=models.TextField(default='No goal specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.member')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.space')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainer')),
            ],
        ),
    ]
