# Generated by Django 4.2.16 on 2024-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_payment_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='serv_desc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='serv_grams',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
