# Generated by Django 4.2.16 on 2024-12-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_remove_trainingsession_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberJoinsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainingsession')),
            ],
            options={
                'unique_together': {('member', 'session')},
            },
        ),
    ]
