# Generated by Django 4.2.16 on 2024-11-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_role_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='Enter Your City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(default='Enter Your State', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='zipcode',
            field=models.CharField(default='Enter Your Zipcode', max_length=10),
            preserve_default=False,
        ),
    ]
