# Generated by Django 4.2.16 on 2024-12-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_memberjoinssession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='is_available',
        ),
    ]
