# Generated by Django 4.2.16 on 2024-11-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_rename_address_member_street_address_member_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(choices=[('Yoga Studio', 'Yoga Studio'), ('Treadmill Room', 'Treadmill Room'), ('Weight Room 1', 'Weight Room 1'), ('Weight Room 2', 'Weight Room 2'), ('Weight Room 3', 'Weight Room 3'), ('Boxing Gym', 'Boxing Gym'), ('CrossFit Gym', 'CrossFit Gym'), ('Wind Tunnel', 'Wind Tunnel'), ('Dance Studio', 'Dance Studio')], max_length=50, unique=True),
        ),
    ]
