# Generated by Django 4.2.16 on 2024-11-17 19:27

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('carbohydrate', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat_total_lipid', models.FloatField()),
                ('kilocalories', models.FloatField()),
            ],
        ),
    ]
