# Generated by Django 5.1.2 on 2024-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_member_user_trainer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberjoinssession',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
