# Generated by Django 4.2.16 on 2024-11-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_food_category_foodlog'),
        ('fitness_app', '0008_auto_20241117_1427'),
    ]

    operations = [
    ]
