# Generated by Django 4.2.16 on 2024-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_alter_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='goal_weight',
            field=models.IntegerField(default=0),
        ),
    ]
