# Generated by Django 4.2.16 on 2024-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0012_remove_member_name_member_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(default='First', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(default='Last', max_length=50),
            preserve_default=False,
        ),
    ]
